package homework1;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Naz Wright
 */

// server boots up 

//loop

// if server has no more guesses exit

	// server guess number generated by client 

	// send number back to client
	
	//repeat
public class Server {
	public static void main(String args[]) throws IOException { 
		DataOutputStream  dos = null;
		DataInputStream dis = null;

		try{
			ServerSocket server = new ServerSocket(5000);
			System.out.println("......Server Started....");
			System.out.println("Waiting for a client");

			String line = "";

			while(true){
				Socket socket = null;
				try{
					// socket object to receive incoming client requests 
                    socket = server.accept();
						// obtaining input and out streams 
		            dis = new DataInputStream(socket.getInputStream());
		            dos = new DataOutputStream(socket.getOutputStream());

		           //handle client here....
		            int maxVal = dis.readInt();
		            int guesses = dis.readInt();
		            System.out.println("received " + maxVal + "and" + guesses + " from client");

		            do{
		            	int inclusive = maxVal + 1; // add one to the max value to include it in the random gen
		            	int guess = (int) (Math.random() * ( maxVal - 1 + 1 ) + 1) ;
		            	dos.writeInt(guess);
		            	System.out.println("My Guess is " + guess);

		            	System.out.println("Client says: " + dis.readInt());
		            	guesses--;
		            }
		            while( guesses > 0 );
		            socket.close();
		          
				}
				catch (Exception e) {
                    socket.close();
                    e.printStackTrace();
                }
				
			}

			
		}
		catch (IOException i) {
            System.out.println(i);
        }
	}
}