package homework1;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Naz Wright
 */

// server boots up 

//loop

// if server has no more guesses exit

	// server guess number generated by client 

	// send number back to client
	
	//repeat
public class Server {
	public static void main(String args[]) throws IOException { 
		DataOutputStream  dos = null;
		DataInputStream dis = null;

		try{
			ServerSocket server = new ServerSocket(5000);
			System.out.println("......Server Started....");
			System.out.println("Waiting for a client");

			String line = "";

			while(true){
				Socket socket = null;
				try{
					socket = server.accept();
					System.out.println("------New Client Connected: " + socket);

						// obtaining input and out streams 
		            dis = new DataInputStream(socket.getInputStream());
		            dos = new DataOutputStream(socket.getOutputStream());

		           //handle client here....
		            int received = dis.readInt();
		            int guesses = dis.readInt();
		            System.out.println("received " + received + "and" + guesses + " from client");

		          
				}
				catch (Exception e) {
                    socket.close();
                    e.printStackTrace();
                }
				
			}

			
		}
		catch (IOException i) {
            System.out.println(i);
        }
	}
}